[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
anchor_counter = "dPRoKkdhQVbQfMtFkfXq1rjZM7ooCpnDpYhMBJGtwy4"

[programs.localnet]
anchor_counter = "dPRoKkdhQVbQfMtFkfXq1rjZM7ooCpnDpYhMBJGtwy4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/zayman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
