[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_novamesh = "7p9LDQG2eXeyHYkkxMX6J9iLQ5gMd4s8xAhqy9PHr7S7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zayman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
