[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "DeffejzE94nG1u4ZoAhGzmS9bWfQ1Sd1RFknj7M2AJa5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zayman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
