[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
anchor_counter = "dPRoKkdhQVbQfMtFkfXq1rjZM7ooCpnDpYhMBJGtwy4"
game-reviews = "Cu82DmpTFM65d5Qqja2cmW3wWnw6CmaKf7aBwt9r5UQU"

[programs.localnet]
anchor_counter = "dPRoKkdhQVbQfMtFkfXq1rjZM7ooCpnDpYhMBJGtwy4"
game-reviews = "Cu82DmpTFM65d5Qqja2cmW3wWnw6CmaKf7aBwt9r5UQU"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zayman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
